######################################
# [No Dummy] Root, Level1, Level2, and Level3
######################################
#- CD_0_0 :
#  - label    : Root
#    interval : 1
#    errortype: 0xF
#    medium: GlobalDisk
#  - CD_1_1 :
#    - label    : main_loop_inner
#      interval : 1
#      errortype: 0xF
#      medium: GlobalDisk
#    - CD_2_2 :
#      - label    : advanceVelocity_start
#        interval : 1
#        errortype: 0x3
#        medium: LocalMemory
#    - CD_2_3 :
#      - label    : advancePosition
#        interval : 1
#        errortype: 0x3
#        medium: LocalMemory
#    - CD_2_4 :
#      - label    : redistributeAtoms
#        interval : 1
#        errortype: 0x3
#        medium: LocalMemory
#    - CD_2_5 :
#      - label    : computeForce
#        interval : 1
#        errortype: 0x3
#        medium: LocalMemory
#      - CD_3_6 :
#        - label    : ljForce_loop
#          interval : 1
#          errortype: 0x1
#          medium: LocalMemory
#    - CD_2_7 :
#      - label    : advanceVelocity_end
#        interval : 1
#        errortype: 0x3
#        medium: LocalMemory
######################################
# [Level2 COMBINED] Root, Level1, Level2, Level3
######################################
#- CD_0_0 :
#  - label    : Root
#    interval : 1
#    errortype: 0xF
#    medium: GlobalDisk
#  - CD_1_1 :
#    - label    : main_loop_inner
#      interval : 1
#      errortype: 0xF
#      medium: GlobalDisk
#    - CD_2_2 :
#      - label    : lv2_combined
#        interval : 1
#        errortype: 0x3
#        medium: LocalMemory
#      - CD_3_3 :
#        - label    : ljForce_loop
#          interval : 1
#          errortype: 0x1
#          medium: LocalMemory
######################################
# Root:   0xF and KHDD
# Level1: 0xF and kDRAM
# Level2: 0xC and kDRAM
######################################
# SC'18 setting
#- FAILURE_FTYPE0 :
#  - F8 : 0.0
#  - F1 : 0.0133
#  - F2 : 0.00267
#  - F4 : 0.000197
#- FAILURE_FTYPE0 :
#  - F8 : 0.0
#  - F1 : 0.133
#  - F2 : 0.267
#  - F4 : 0.0197
# IPDPS'18 setting
- FAILURE_Ftype0 :
  - F1 : 0.0133
  - F2 : 0.00267
  - F4 : 0.000197
  - F8 : 0.0001053
