######################################
# Root CD and Level 1 CD
######################################
#- CD_0_0 :
#  - label : root_cd
#    interval : 1
#    errortype : 0xF
#    medium: GlobalDisk
#  - CD_1_1 :
#    - label : cd_l1_mgbuild
#      interval : 1
#      errortype : 0xF
#      medium: GlobalDisk
#  - CD_1_2 :
#    - label : cd_l1
#      interval : 1
#      errortype : 0xF
#      medium: GlobalDisk
#    - CD_2_2 :
#      - label : cd_fmgsolve
#        interval : 1
#        errortype : 0x3
#        medium: LocalMemory
#    - CD_2_3 :
#      - label : cd_coarsest_grid
#        interval : 1
#        errortype : 0x3
#        medium: LocalMemory
#    - CD_2_4 :
#      - label : cd_mgvcycle
#        interval : 1
#        errortype : 0x3
#        medium: LocalMemory
#    - CD_2_5 :
#      - label : cd_postf_vcycle
#        interval : 1
#        errortype : 0x3
#        medium: LocalMemory

######################################
# Root:   0xF and KHDD
# Level1: 0xF and kDRAM
# Level2: 0xC and kDRAM
######################################

- FAILURE_Ftype0 :
  - F1 : 0.0133
  - F2 : 0.00267
  - F4 : 0.000197
  - F8 : 0.0001053

