######################################
# Root CD 
######################################
- CD_0_0 :
  - label    : Root
    interval : 1
    errortype: 0xF

- FAILURE :
  - F1 : 0.000
  - F2 : 0.000
  - F4 : 0.00 
  - F8 : 1.00

